# NixOS configuration for host: bandit
#
# Hardware: Framework 13 AMD (7040 series)
# Storage:  BTRFS with subvolumes (@, @home, @nix, @var, @swap)
# Features: Desktop (i3+XFCE), Laptop optimizations, Stylix theming

{
  inputs,
  lib,
  ...
}:
let
  mainDisk = "/dev/disk/by-uuid/0629aaee-1698-49d1-b3e1-e7bb6b957cda";
  resumeOffset = "1959063";
  # Directories excluded from ClamAV scans on this host.
  clamavExcludePaths = [
    "/home/vino/Documents/Projekts/mrijaPage" # active web project — many small files
  ];
  cfgLib = import ../../lib { inherit lib; };
  # BTRFS mount options — see lib/default.nix for the full definition.
  inherit (cfgLib) mkBtrfsOpts;

in
{
  imports = [
    inputs.nixos-hardware.nixosModules.framework-13-7040-amd
    ./hardware-configuration.nix
    inputs.nix-index-database.nixosModules.nix-index
    ../../nixos-modules/home-manager.nix
  ];

  networking.hostName = "bandit";
  services.dbus.implementation = "dbus";
  system.stateVersion = "25.11";

  # Feature modules
  features = {
    services = {
      tailscale = {
        enable = true;
        useRoutingFeatures = "client";
      };

      # Monitoring (currently disabled for battery life)
      monitoring = {
        enable = false;
        grafana.enable = false;
        logging.enhancedJournal = true; # Runs independently of monitoring.enable (separate guard in module)
      };

      # Automated updates (timer disabled for battery life)
      auto-update = {
        enable = true; # Service available for manual triggering
        timer.enable = false; # Disabled for battery (2-4% per update, 10-15min CPU)
        timer.calendar = "monthly"; # When enabled, run monthly
      };

    };

    desktop.i3-xfce = {
      enable = true;
      keyboardLayout = "at"; # Austrian keyboard
    };

    storage = {
      boot = {
        enable = true;
        bootloader = "grub";
        kernelPackage = "latest";
      };

      swap = {
        enable = true;
        devices = [
          {
            device = "/swap/swapfile";
            priority = 1; # Lower priority - use as backup after zram is full
          }
        ];
      };

      btrfs = {
        enable = true;
        fstrim.enable = true;
        autoScrub = {
          enable = true;
          fileSystems = [
            "/"
            "/home"
          ];
          interval = "monthly";
        };
      };

      snapper = {
        enable = true;
        enableTimeline = false; # Disabled for I/O reduction — manual snapshots preferred
        configs = {
          root = {
            subvolume = "/";
            numberLimit = "50";
          };
          home = {
            subvolume = "/home";
            numberLimit = "50";
          };
        };
      };
    };

    theme.stylix = {
      enable = true;
      targets.grub.enable = true;
      targets.lightdm.enable = true;
    };

    hardware.laptop = {
      enable = true;
      cpu.vendor = "amd";
      # useAutoFreq intentionally not set (defaults to false) — auto-cpufreq caused
      # instability on this machine; using power-profiles-daemon instead.
      powerManagement.enableHibernation = true;
      zram = {
        memoryPercent = 50; # Increase from 25% to 50% for better memory headroom
      };
      framework = {
        enable = true;
        model = "framework-13-amd";
      };
    };

    development.base = {
      enable = true;
      virtualization.docker.enable = true;
      virtualization.podman.enable = false;
      wireshark.enable = true;
    };

    security = {
      secrets.enable = true;

      # Desktop security hardening
      desktop-hardening = {
        enable = true;
        # Disable kernel image protection to allow hibernation.
        # kexec is still blocked via sysctl in desktop-hardening regardless of this setting.
        protectKernelImage = false;
        firewall.allowedTCPPorts = [ 8181 ];
      };

      clamav = {
        enable = true;
        excludePaths = clamavExcludePaths;
      };
    };
  };

  # Hibernation support (swapfile on BTRFS).
  # resumeDevice:  UUID of the BTRFS partition containing the swapfile.
  # resume_offset: Physical offset of the swapfile (obtained via `filefrag -v /swap/swapfile`).
  #                Required for kernel to resume from hibernation.
  boot = {
    resumeDevice = mainDisk;
    # Host-specific swapfile offset; regenerate if /swap/swapfile is recreated:
    #   sudo filefrag -v /swap/swapfile | awk 'NR==4{gsub(/\.\./,""); print $4}'
    kernelParams = [ "resume_offset=${resumeOffset}" ];

    # NixOS 26.05 changed boot.initrd.systemd.enable to default=true, but the
    # systemd initrd has an unresolved incompatibility with separate BTRFS subvolumes
    # on a shared UUID (sysroot-nix.mount not generated by fstab-generator, and
    # explicit mounts don't survive the stage-1→stage-2 transition cleanly).
    # Scripted initrd handles this correctly. Re-evaluate when upgrading past 26.11
    # (scripted initrd is scheduled for removal in 26.11).
    # Tracked upstream: NixOS/nixpkgs #202846, #428775.
    initrd.systemd.enable = false;
  };

  # Filesystem mounts — optimized BTRFS options override hardware-configuration.nix.
  # Main disk uses mkBtrfsOpts for consistent SSD + battery optimization.
  fileSystems = {
    "/" = {
      device = mainDisk;
      fsType = "btrfs";
      options = lib.mkForce (mkBtrfsOpts "@"); # Force options to override hardware-configuration.nix
    };
    "/home" = {
      device = mainDisk;
      fsType = "btrfs";
      options = lib.mkForce (mkBtrfsOpts "@home"); # Force options to override hardware-configuration.nix
    };
    "/nix" = {
      device = mainDisk;
      fsType = "btrfs";
      options = lib.mkForce (mkBtrfsOpts "@nix"); # Force options to override hardware-configuration.nix
    };
    "/var" = {
      device = mainDisk;
      fsType = "btrfs";
      options = lib.mkForce (mkBtrfsOpts "@var"); # Force options to override hardware-configuration.nix
    };
  };
}
