# Host-specific machine parameters for: bandit (Framework 13 AMD)
#
# Boundary: This file owns all machine-specific facts that cannot be derived
# from hardware-configuration.nix or feature modules. It is the single source
# of truth for values that are tied to this physical machine's storage layout,
# firmware state, and host-specific exclusions.
#
# Values here are intentionally NOT in default.nix (composition) or
# hardware-configuration.nix (generated) because they require human judgment
# to set and must survive hardware-configuration.nix regeneration.
#
# Contained here:
#   mainDisk       — BTRFS partition UUID (same device as hardware-configuration.nix,
#                    referenced explicitly here for hibernation + mount-option overrides)
#   resumeOffset   — swapfile physical offset for kernel hibernation resume
#                    (regenerate with: sudo filefrag -v /swap/swapfile | awk 'NR==4{gsub(/\.\./,""); print $4}')
#   clamavExcludePaths — host-specific directories excluded from ClamAV scans
#   fileSystems    — BTRFS mount-option overrides (SSD + battery optimized, via mkBtrfsOpts)
#   boot           — hibernation resume device/offset + initrd workaround for BTRFS subvolumes
{
  lib,
  ...
}:
let
  # BTRFS partition UUID — shared by all subvolumes on this machine.
  # Same device as hardware-configuration.nix; referenced here for overrides.
  mainDisk = "/dev/disk/by-uuid/0629aaee-1698-49d1-b3e1-e7bb6b957cda";

  # Physical offset of /swap/swapfile within the BTRFS partition.
  # Required by the kernel to locate the swapfile during hibernation resume.
  # Regenerate if /swap/swapfile is recreated:
  #   sudo filefrag -v /swap/swapfile | awk 'NR==4{gsub(/\.\./,""); print $4}'
  resumeOffset = "1959063";

  # Directories excluded from ClamAV scans on this host.
  clamavExcludePaths = [
    "/home/vino/Documents/Projekts/mrijaPage" # active web project — many small files
  ];

  cfgLib = import ../../lib { inherit lib; };
  inherit (cfgLib) mkBtrfsOpts;
in
{
  # Pass clamavExcludePaths to the security feature module.
  features.security.clamav.excludePaths = clamavExcludePaths;

  # Hibernation support (swapfile on BTRFS).
  # resumeDevice:  UUID of the BTRFS partition containing the swapfile.
  # resume_offset: Physical offset of the swapfile (see above).
  #                Required for kernel to resume from hibernation.
  boot = {
    resumeDevice = mainDisk;
    kernelParams = [ "resume_offset=${resumeOffset}" ];

    # NixOS 26.05 changed boot.initrd.systemd.enable to default=true, but the
    # systemd initrd has an unresolved incompatibility with separate BTRFS subvolumes
    # on a shared UUID (sysroot-nix.mount not generated by fstab-generator, and
    # explicit mounts don't survive the stage-1->stage-2 transition cleanly).
    # Scripted initrd handles this correctly. Re-evaluate when upgrading past 26.11
    # (scripted initrd is scheduled for removal in 26.11).
    # Tracked upstream: NixOS/nixpkgs #202846, #428775.
    initrd.systemd.enable = false;
  };

  # Filesystem mounts — optimized BTRFS options override hardware-configuration.nix.
  # Main disk uses mkBtrfsOpts for consistent SSD + battery optimization.
  fileSystems = {
    "/" = {
      device = mainDisk;
      fsType = "btrfs";
      options = lib.mkForce (mkBtrfsOpts "@"); # Force options to override hardware-configuration.nix
    };
    "/home" = {
      device = mainDisk;
      fsType = "btrfs";
      options = lib.mkForce (mkBtrfsOpts "@home"); # Force options to override hardware-configuration.nix
    };
    "/nix" = {
      device = mainDisk;
      fsType = "btrfs";
      options = lib.mkForce (mkBtrfsOpts "@nix"); # Force options to override hardware-configuration.nix
    };
    "/var" = {
      device = mainDisk;
      fsType = "btrfs";
      options = lib.mkForce (mkBtrfsOpts "@var"); # Force options to override hardware-configuration.nix
    };
  };
}
